# Generated by Django 3.2 on 2021-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batch', models.BigIntegerField()),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
